# Servidor
server.port=8081
spring.application.name=ms-reportes

# PostgreSQL - db_reportes
spring.datasource.url=jdbc:postgresql://localhost:5432/db_reportes
spring.datasource.username=postgres
spring.datasource.password=Kevin2209.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs
logging.level.com.sanosysalvos=DEBUG