# Servidor
server.port=8082
spring.application.name=ms-usuarios

# PostgreSQL - db_usuarios
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarios
spring.datasource.username=postgres
spring.datasource.password=Kevin2209.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=sanos-y-salvos-secret-key-2025-muy-larga-para-seguridad-256bits
jwt.expiration=86400000

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web=DEBUG