server.port=8083
spring.application.name=ms-coincidencias

spring.datasource.url=jdbc:postgresql://localhost:5432/db_reportes
spring.datasource.username=postgres
spring.datasource.password=Kevin2209.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL del MS Reportes para consultar datos
ms.reportes.url=http://localhost:8081

logging.level.com.sanosysalvos=DEBUG